apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-kafka
  name: greetings-sample
spec:
  config:
    min.insync.replicas: "2"
  partitions: 3
  replicas: 3
  topicName: greetings-sample
