spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka-kafka-bootstrap:9092
          # brokers: localhost:9092
          auto-create-topics: false
          configuration:
            auto.offset.reset: latest
      bindings:
        greetings-in:
          destination: greetings-sample
          group: greetings-group
          contentType: application/json
        greetings-out:
          destination: greetings-sample
          contentType: application/json
